name: Run Tests
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - uses: chartboost/ruff-action@v1
        with:
          args: check .
  test:
    name: Run Tests${{ matrix.keria-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    env:
      KERIA_IMAGE_TAG: ${{ matrix.keria-version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python 3.12.2
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2
      - name: Install libsodium
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov hio httpx
          pip install -r requirements.txt
      - name: Start dependencies
        run: |
          sudo docker compose up -d vlei-verifier
          sudo docker compose up -d --build reg-pilot-api
      - name: Run unit tests wit coverage
        run: pytest --cov=./src/regps/app --cov-report=term-missing --cov-fail-under=50


